SET DEFINE OFF;

--챔피언
INSERT INTO CHAMPION VALUES('Aatrox','the Darkin Blade','Fighter','Runeterra','2013-06-13');
INSERT INTO CHAMPION VALUES('Ahri','the Nine-Tailed Fox','Mage','Ionia','2011-12-14');
INSERT INTO CHAMPION VALUES('Akali','the Rogue Assassin','Slayer','Ionia','2010-05-11');
INSERT INTO CHAMPION VALUES('Akshan','the Rogue Sentinel','Marksman','Shurima','2021-07-22');
INSERT INTO CHAMPION VALUES('Alistar','the Minotaur','Tank','Runeterra','2009-02-21');
INSERT INTO CHAMPION VALUES('Amumu','the Sad Mummy','Tank','Shurima','2009-06-26');
INSERT INTO CHAMPION VALUES('Anivia','the Cryophoenix','Mage','Freljord','2009-07-10');
INSERT INTO CHAMPION VALUES('Annie','the Dark Child','Mage','Runeterra','2009-02-21');
INSERT INTO CHAMPION VALUES('Aphelios','the Weapon of the Faithful','Marksman','Targon','2019-12-11');
INSERT INTO CHAMPION VALUES('Ashe','the Frost Archer','Marksman','Freljord','2009-02-21');
INSERT INTO CHAMPION VALUES('Aurelion Sol','The Star Forger','Mage','Runeterra','2016-03-24');
INSERT INTO CHAMPION VALUES('Azir','the Emperor of the Sands','Specialist','Shurima','2014-09-16');
INSERT INTO CHAMPION VALUES('Bard','the Wandering Caretaker','Controller','Runeterra','2015-03-12');
INSERT INTO CHAMPION VALUES('Bel''veth','The Empress of the Void','Slayer','The Void','2022-06-09');
INSERT INTO CHAMPION VALUES('Blitzcrank','the Great Steam Golem','Controller','Zaun','2009-09-02');
INSERT INTO CHAMPION VALUES('Brand','the Burning Vengeance','Mage','Runeterra','2011-04-12');
INSERT INTO CHAMPION VALUES('Braum','the Heart of the Freljord','Tank','Freljord','2014-05-12');
INSERT INTO CHAMPION VALUES('Caitlyn','the Sheriff of Piltover','Marksman','Piltover','2011-01-04');
INSERT INTO CHAMPION VALUES('Camille','the Steel Shadow','Fighter','Piltover','2016-12-07');
INSERT INTO CHAMPION VALUES('Cassiopeia','the Serpent''s Embrace','Mage','Noxus','2010-12-14');
INSERT INTO CHAMPION VALUES('Cho''gath','the Terror of the Void','Specialist','The Void','2009-06-26');
INSERT INTO CHAMPION VALUES('Corki','the Daring Bombardier','Marksman','Bandle City','2009-09-19');
INSERT INTO CHAMPION VALUES('Darius','the Hand of Noxus','Fighter','Noxus','2012-05-23');
INSERT INTO CHAMPION VALUES('Diana','Scorn of the Moon','Slayer','Targon','2012-08-07');
INSERT INTO CHAMPION VALUES('Dr.Mundo','the Madman of Zaun','Fighter','Zaun','2009-09-02');
INSERT INTO CHAMPION VALUES('Draven','the Glorious Executioner','Marksman','Noxus','2012-06-06');
INSERT INTO CHAMPION VALUES('Ekko','the Boy Who Shattered Time','Slayer','Zaun','2015-05-29');
INSERT INTO CHAMPION VALUES('Elise','the Spider Queen','Fighter','Shadow Isles','2012-10-26');
INSERT INTO CHAMPION VALUES('Evelynn','Agony''s Embrace','Slayer','Runeterra','2009-05-01');
INSERT INTO CHAMPION VALUES('Ezreal','the Prodigal Explorer','Marksman','Piltover','2010-03-16');
INSERT INTO CHAMPION VALUES('Fiddlesticks','the Ancient Fear','Specialist','Runeterra','2009-02-21');
INSERT INTO CHAMPION VALUES('Fiora','the Grand Duelist','Slayer','Demacia','2012-02-29');
INSERT INTO CHAMPION VALUES('Fizz','the Tidal Trickster','Slayer','Runeterra','2011-11-15');
INSERT INTO CHAMPION VALUES('Galio','the Colossus','Tank','Demacia','2010-08-10');
INSERT INTO CHAMPION VALUES('Gangplank','the Saltwater Scourge','Specialist','Bilgewater','2009-08-19');
INSERT INTO CHAMPION VALUES('Garen','The Might of Demacia','Fighter','Demacia','2010-04-27');
INSERT INTO CHAMPION VALUES('Gnar','the Missing Link','Specialist','Freljord','2014-08-14');
INSERT INTO CHAMPION VALUES('Gragas','the Rabble Rouser','Tank','Freljord','2010-02-02');
INSERT INTO CHAMPION VALUES('Graves','the Outlaw','Specialist','Bilgewater','2011-10-19');
INSERT INTO CHAMPION VALUES('Gwen','The Hallowed Seamstress','Slayer','Shadow Isles','2021-04-15');
INSERT INTO CHAMPION VALUES('Hecarim','the Shadow of War','Fighter','Shadow Isles','2012-04-18');
INSERT INTO CHAMPION VALUES('Heimerdinger','the Revered Inventor','Specialist','Piltover','2009-10-10');
INSERT INTO CHAMPION VALUES('Illaoi','the Kraken Priestess','Fighter','Bilgewater','2015-11-24');
INSERT INTO CHAMPION VALUES('Irelia','the Blade Dancer','Fighter','Ionia','2010-11-16');
INSERT INTO CHAMPION VALUES('Ivern','the Green Father','Controller','Ionia','2016-10-05');
INSERT INTO CHAMPION VALUES('Janna','the Storm''s Fury','Controller','Zaun','2009-09-02');
INSERT INTO CHAMPION VALUES('Jarvan IV','the Exemplar of Demacia','Fighter','Demacia','2011-03-01');
INSERT INTO CHAMPION VALUES('Jax','Grandmaster at Arms','Slayer','Runeterra','2009-02-21');
INSERT INTO CHAMPION VALUES('Jayce','the Defender of Tomorrow','Mage','Piltover','2012-07-07');
INSERT INTO CHAMPION VALUES('Jhin','the Virtuoso','Marksman','Ionia','2016-02-01');


--스킨 세계관
INSERT INTO SKIN_UNIVERSE VALUES('justicar','The main universe in which most known characters reside in. It is also the universe with the most stories and general lore more commonly referred to as the 
"canon" lore.');
INSERT INTO SKIN_UNIVERSE VALUES('arcana','From the stories told during the Ionian Spirit Blossom festivals, as well as a possible afterlife in the Ionian mythos. Champions represent the characters from those stories. ');
INSERT INTO SKIN_UNIVERSE VALUES('dynasty','Character appearances during the Return of the Ruined King story events.');
INSERT INTO SKIN_UNIVERSE VALUES('k-da','A universe with an alternate depiction of Runeterra. City states are mediated by the Institute of War, a powerful organization controlled by mages known as the Summoners. Champions from each city and area of Runeterra come to the Institute to fight in the Map (League of Legends)Fields of Justice for personal or faction goals. It is also the universe which is commonly referred to as the "old" lore.');
INSERT INTO SKIN_UNIVERSE VALUES('cyber-pop','A universe with an alternate depiction of Runeterra and the main setting of the Arcane (TV Series)Arcane series.');
INSERT INTO SKIN_UNIVERSE VALUES('conqueror','A universe Or universes, depending on how many have started and ended at the hands of Cosmic and Dark Star entities. of galaxy spanning entities of creation and destruction. It has connections with the characters from the Odyssey universe.');
INSERT INTO SKIN_UNIVERSE VALUES('hextech','A universe with a western-like society filled with cowboys, steampunk robots, angels, and demons.');
INSERT INTO SKIN_UNIVERSE VALUES('cosmic-flight','A universe with an alternate depiction of Ionia. Characters are zealous cultists and demons who worship or originate from mysterious blood-red or snow-white moons.');
INSERT INTO SKIN_UNIVERSE VALUES('red-riding','A contemporary universe similar to real-life Earth where virtual bands or solo musicians are comprised of League of Legends champions which are performed 
by popular musicians. Each member of the band has a skin corresponding to their music alter-ego. Music made by these characters also appears in multiple universes.');
INSERT INTO SKIN_UNIVERSE VALUES('spirit-blossom','A science-fiction universe with a vast galactic civilization dependent of a mysterious golden essence known as ora. It has connections with the entities of the Event Horizon universe and characters from the Astronauts universe.');
INSERT INTO SKIN_UNIVERSE VALUES('high-noon','A science-fiction dystopian universe of cybernetically augmented humans, mega-corporations, and artificial intelligence with its own goals. ');
INSERT INTO SKIN_UNIVERSE VALUES('storm-dragon','A science-fiction dystopian universe where Chrono-enforcers of a regimental totalitarian order known as The Remembrancers control time and space. Characters from this universe are able to traverse each and every universe and timeline. Time meddling done by Chrono-fugitives can damage timelines, creates paradoxes, and creates numerous other timelines which can lead to the complete destruction of multiple timelines and universe in the hands of the chaotic Praetorians.');
INSERT INTO SKIN_UNIVERSE VALUES('galactic','A universe with anime inspired magically empowered school characters that fight evil doers across the galaxy. It is also a popular manga series in multiple 
universes.');
INSERT INTO SKIN_UNIVERSE VALUES('Others','Others etc');
INSERT INTO SKIN_UNIVERSE VALUES('battle-boss','A contemporary universe of near-future Earth where radiants changed the world. While not intrinsically part the wider Runeterran multiverse, it has already interacted and connected with it through events such as RiotX Arcane and with the existence of tipLeague of Legends as a video game within it.');
INSERT INTO SKIN_UNIVERSE VALUES('goalkeeper','A universe with characters that are part of a contemporary school environment.');
INSERT INTO SKIN_UNIVERSE VALUES('vandal','A fantasy universe of elves. It has connection to UnivRift Quest.');
INSERT INTO SKIN_UNIVERSE VALUES('sugar-rush','An alternative/near-future universe in which the Anima Squad faces an invasion of the former high-tech army of the Primordians on a dying Earth.');       
INSERT INTO SKIN_UNIVERSE VALUES('pool-party','A contemporary universe where characters celebrate games made by Riot Games.');
INSERT INTO SKIN_UNIVERSE VALUES('strike-commander','A universe where characters interact with digital video game entities. It has connections with the UnivDemacia Vice universe, which is one of many existing video games.');
INSERT INTO SKIN_UNIVERSE VALUES('coven','A fantasy universe where characters are Archetypes that want to shape the world to their vision.');
INSERT INTO SKIN_UNIVERSE VALUES('prehistoric','A fantasy universe of mages. It has connection to UnivRift Quest.');
INSERT INTO SKIN_UNIVERSE VALUES('sentinel','A universe with ancient, godlike entities that descend from the heaves, choosing worthy warriors of the light divine.');
INSERT INTO SKIN_UNIVERSE VALUES('ruined','An alternate Runeterra universe with a space exploration program. It has some connections with the space adventurers of the Odyssey universe.');
INSERT INTO SKIN_UNIVERSE VALUES('frozen-prince-mundo','A universe with anime inspired school characters training to be future heroes.');
INSERT INTO SKIN_UNIVERSE VALUES('firelight','A fantasy world where queens reign and participate in 
the Coronation that determines the fate of their Queendom.');
INSERT INTO SKIN_UNIVERSE VALUES('bewitching','A science-fiction dystopian universe also referred to as the murderbot timeline. It is a universe where ciViktor achieved his glorious evolution. May have some connections with UnivEternum.');
INSERT INTO SKIN_UNIVERSE VALUES('tango','A universe where characters are bees, dressed as bees, or 
are beekeepers. It has connections to UnivPool Party.');
INSERT INTO SKIN_UNIVERSE VALUES('ssg','A universe with an alternate depiction of Bilgewater. Characters from different Runeterra regions are depicted in the Bilgewater style. Some character visual depictions in this universe also appear in the Runeterra Prime universe.');
INSERT INTO SKIN_UNIVERSE VALUES('praetorian','A universe with an alternate depiction of Freljord where characters are corrupted by the Watcherpower of the ciLissandraIce Witch.');
INSERT INTO SKIN_UNIVERSE VALUES('ig',' A universe of zealous cultists who worship the hallowed Bloodstone.');
INSERT INTO SKIN_UNIVERSE VALUES('super-galaxy','A universe with characters depicted as ether cats or dogs. It has connection to UnivThe Grind, UnivRiot Records and univTales from the Rift.');
INSERT INTO SKIN_UNIVERSE VALUES('commando','A universe in which entities of chaos and order clash with each other in a never ending battle for dominance.');
INSERT INTO SKIN_UNIVERSE VALUES('mecha-kingdoms','A fantasy universe where characters are empowered by lightning magic.');
INSERT INTO SKIN_UNIVERSE VALUES('elderwood','A universe with specialized military warriors and guerilla fighters.');
INSERT INTO SKIN_UNIVERSE VALUES('warden','A universe with an alternate depiction of Piltover. It has a contemporary appearing police force, criminal underground, and secret agents.');
INSERT INTO SKIN_UNIVERSE VALUES('hired-gun',' ');
INSERT INTO SKIN_UNIVERSE VALUES('dragon-trainer','A universe with Easter Bunny-like characters.'); 
INSERT INTO SKIN_UNIVERSE VALUES('cosmic-invoker','A universe where characters are mobsters who vie 
for control of a city, turning to mysterious figures with powers of an ancient evil.');
INSERT INTO SKIN_UNIVERSE VALUES('project','A universe with an alternate depiction of Noxus.');     
INSERT INTO SKIN_UNIVERSE VALUES('dunkmaster','A fantasy world where individuals attend the annual Crystal Rose Festival to form alliances and negotiate truces.');
INSERT INTO SKIN_UNIVERSE VALUES('cyber-halo','A universe with a popular TV cooking show. The TV show also appears in at least 50 other universes.');
INSERT INTO SKIN_UNIVERSE VALUES('worlds-2021','A futuristic where augmented punk characters band together against corporate overlords.');
INSERT INTO SKIN_UNIVERSE VALUES('god-staff','A universe where fallen warriors return to the plane 
of the living to claim even more souls for the Underworld.');
INSERT INTO SKIN_UNIVERSE VALUES('dark-cosmic','Definitely not an alternate universe... right?');   
INSERT INTO SKIN_UNIVERSE VALUES('resistance','A universe with an alternate depiction of Demacia, with real-life Earth appearance of 80s police flicks. It is also a video game in the Arcade universe.');
INSERT INTO SKIN_UNIVERSE VALUES('lunar-eclipse','A universe commonly referred to as Hell. It has connections with the Tales from the Rift (Universe)Harrowing alternate universe via summoning of TeemoLittle Devil.');
INSERT INTO SKIN_UNIVERSE VALUES('mecha','A universe where characters wield the the powers of dragons. Has some connections to the Spirit Guard universe.');
INSERT INTO SKIN_UNIVERSE VALUES('odyssey','A universe where dragons roam free in vast numbers. Characters are ether allied with the dragons or against them.');
INSERT INTO SKIN_UNIVERSE VALUES('sea-hunter','A universe with an alternate depiction of Freljord. Characters are part of an undead knight order.');
INSERT INTO SKIN_UNIVERSE VALUES('victorious',' A contemporary universe where characters are popular 
basketball players.');
INSERT INTO SKIN_UNIVERSE VALUES('blood-moon','A fantasy universe with monastic knights and eldritch gods of an old world. UnivOmen of the Dark is a story book in this universe.');
INSERT INTO SKIN_UNIVERSE VALUES('crime-city-nightmare','A universe with an alternate depiction of Demacia. LuxElementalistA mage queen rules over Demacia and does everything in her power to protect it.');
INSERT INTO SKIN_UNIVERSE VALUES('stinger','A science-fiction universe with indoctrinated alien machines. May have some connections with UnivBattlecast.');
INSERT INTO SKIN_UNIVERSE VALUES('k-da-all-out','A universe where mythical creatures and legends exist.');
INSERT INTO SKIN_UNIVERSE VALUES('infernal','A universe where characters are parts of Lunar Revel festivities.');
INSERT INTO SKIN_UNIVERSE VALUES('true-damage','A universe with eldritch horrors and legends from the deep oceans. ');
INSERT INTO SKIN_UNIVERSE VALUES('all-star','A universe with an alternate rendition of the Freljord. Some character visual depictions in this universe also appear in the Runeterra Prime universe.');   
INSERT INTO SKIN_UNIVERSE VALUES('nurse',' ');
INSERT INTO SKIN_UNIVERSE VALUES('cosmic-queen','A Runeterra universe with an alternate depiction of Piltover. Characters represent themselves if the city was never damaged by the creation of the Sun Gates (no creation of the undercity).');
INSERT INTO SKIN_UNIVERSE VALUES('woad','A universe with an alternate depiction of the Freljord. Each character is a creature of ice and snow.');
INSERT INTO SKIN_UNIVERSE VALUES('championship','A contemporary universe with characters part of the Goth/Gothic cultural movement.');
INSERT INTO SKIN_UNIVERSE VALUES('queen','A contemporary universe where League of Legends characters have normal real-life Earth jobs. It has connections to UnivCats Versus Dogs and UnivMusic skins.');INSERT INTO SKIN_UNIVERSE VALUES('amethyst','A universe with an alternate depiction of Shurima. Characters are tomb raiders, ancient tomb guardians, and evil spirits of the desert.');

-- 스킨
INSERT INTO SKIN VALUES('Justicar Aatrox',975,'2013-06-13','False','Regular','Aatrox','justicar');
INSERT INTO SKIN VALUES('Arcana Ahri',1350,'2022-04-14','True','Epic','Ahri','arcana');
INSERT INTO SKIN VALUES('Dynasty Ahri',975,'2011-12-14','True','Regular','Ahri','dynasty');
INSERT INTO SKIN VALUES('K/DA Akali',1350,'2018-11-03','False','Epic','Akali','k-da');
INSERT INTO SKIN VALUES('Cyber Pop Akshan',1350,'2021-07-22','True','Epic','Akshan','cyber-pop');
INSERT INTO SKIN VALUES('Conqueror Alistar',975,'2019-04-30','True','Regular','Alistar','conqueror');
INSERT INTO SKIN VALUES('Hextech Amumu',null,'2019-09-26','False','Mythic','Amumu','hextech');
INSERT INTO SKIN VALUES('Cosmic Flight Anivia',1350,'2020-11-24','True','Epic','Anivia','cosmic-flight');
INSERT INTO SKIN VALUES('Red Riding Annie',520,'2010-04-27','False','Regular','Annie','red-riding');
INSERT INTO SKIN VALUES('Spirit Blossom Aphelios',1350,'2022-10-06','False','Epic','Aphelios','spirit-blossom');
INSERT INTO SKIN VALUES('High Noon Ashe',1820,'2019-10-10','True','Legendary','Ashe','high-noon');
INSERT INTO SKIN VALUES('Storm Dragon Aurelion Sol',1350,'2020-10-01','False','Epic','Aurelion Sol','storm-dragon');
INSERT INTO SKIN VALUES('Galactic Azir',975,'2014-09-16','False','Regular','Azir','galactic');
INSERT INTO SKIN VALUES('Bard Bard',750,'2016-11-17','False','Regular','Bard','Others');
INSERT INTO SKIN VALUES('Battle Boss Bel''Veth',1350,'2022-06-09','True','Epic','Bel''veth','battle-boss');
INSERT INTO SKIN VALUES('Goalkeeper Blitzcrank',520,'2010-06-22','False','Regular','Blitzcrank','goalkeeper');
INSERT INTO SKIN VALUES('Vandal Brand',520,'2011-04-12','False','Regular','Brand','vandal');
INSERT INTO SKIN VALUES('Sugar Rush Braum',1350,'2019-12-17','True','Epic','Braum','sugar-rush');
INSERT INTO SKIN VALUES('Pool Party Caitlyn',1350,'2018-08-02','True','Epic','Caitlyn','pool-party');
INSERT INTO SKIN VALUES('Strike Commander Camille',1350,'2022-08-24','True','Epic','Camille','strike-commander');
INSERT INTO SKIN VALUES('Coven Cassiopeia',1350,'2021-08-12','True','Epic','Cassiopeia','coven');
INSERT INTO SKIN VALUES('Prehistoric cho''gath',750,'2015-06-15','False','Regular','Cho''gath','prehistoric');
INSERT INTO SKIN VALUES('Corgi Corki',1350,'2019-03-27','True','Epic','Corki','Others');
INSERT INTO SKIN VALUES('Spirit Blossom Darius',1350,'2022-10-06','False','Epic','Darius','spirit-blossom');
INSERT INTO SKIN VALUES('Sentinel Diana',1350,'2021-07-08','True','Epic','Diana','sentinel');
INSERT INTO SKIN VALUES('Ruined Draven',1350,'2021-01-21','True','Epic','Draven','ruined');
INSERT INTO SKIN VALUES('Frozen Prince Mundo',1350,'2018-12-06','True','Epic','Dr.Mundo','frozen-prince-mundo');
INSERT INTO SKIN VALUES('Firelight Ekko',1350,'2022-02-17','True','Epic','Ekko','firelight');
INSERT INTO SKIN VALUES('Bewitching Elise',1350,'2020-10-22','True','Epic','Elise','bewitching');
INSERT INTO SKIN VALUES('Tango Evelynn',520,'2010-10-05','False','Regular','Evelynn','tango');
INSERT INTO SKIN VALUES('SSG Ezreal',1350,'2018-07-20','False','Epic','Ezreal','ssg');
INSERT INTO SKIN VALUES('Praetorian Fiddlesticks',1350,'2018-11-08','True','Epic','Fiddlesticks','praetorian');
INSERT INTO SKIN VALUES('iG Fiora',1350,'2019-04-23','False','Epic','Fiora','ig');
INSERT INTO SKIN VALUES('Super Galaxy Fizz',1350,'2016-05-26','False','Epic','Fizz','super-galaxy');
INSERT INTO SKIN VALUES('Commando Galio',520,'2011-01-18','False','Regular','Galio','commando');
INSERT INTO SKIN VALUES('Pool Party Gangplank',1350,'2018-08-02','True','Epic','Gangplank','pool-party');
INSERT INTO SKIN VALUES('Mecha Kingdoms Garen',1350,'2020-01-15','False','Epic','Garen','mecha-kingdoms');
INSERT INTO SKIN VALUES('Elderwood Gnar',1350,'2022-01-06','True','Epic','Gnar','elderwood');
INSERT INTO SKIN VALUES('Warden Gragas',1350,'2021-01-07','True','Epic','Gragas','warden');
INSERT INTO SKIN VALUES('Hired Gun Graves',520,'2011-10-19','False','Regular','Graves','hired-gun');
INSERT INTO SKIN VALUES('High Noon Hecarim',1350,'2019-10-09','True','Epic','Hecarim','high-noon');
INSERT INTO SKIN VALUES('Dragon Trainer Heimerdinger',1820,'2018-10-11','False','Legendary','Heimerdinger','dragon-trainer');
INSERT INTO SKIN VALUES('Cosmic Invoker Illaoi',1350,'2020-11-24','True','Epic','Illaoi','cosmic-invoker');
INSERT INTO SKIN VALUES('PROJECT: Irelia',1350,'2019-08-01','False','Epic','Irelia','project');
INSERT INTO SKIN VALUES('Dunkmaster Ivern',1350,NULL,'True','Epic','Ivern','dunkmaster');
INSERT INTO SKIN VALUES('Cyber Halo Janna',1350,'2022-08-24','True','Epic','Janna','cyber-halo');
INSERT INTO SKIN VALUES('Worlds 2021 Jarvan IV',1350,'2021-09-23','False','Epic','Jarvan IV','worlds-2021');
INSERT INTO SKIN VALUES('God Staff Jax',1350,'2018-01-11','False','Epic','Jax','god-staff');
INSERT INTO SKIN VALUES('Dark Cosmic Jhin',1820,'2019-06-13','False','Legendary','Jhin','dark-cosmic');
INSERT INTO SKIN VALUES('Resistance Jayce',1350,'2020-11-12','True','Epic','Jayce','resistance');
INSERT INTO SKIN VALUES('Lunar Eclipse Aatrox',1350,'2022-04-27','True','Epic','Aatrox','lunar-eclipse');
INSERT INTO SKIN VALUES('Mecha Aatrox',1350,'2014-07-24','True','Epic','Aatrox','mecha');
INSERT INTO SKIN VALUES('Odyssey Aatrox',1350,'2020-10-15','True','Epic','Aatrox','odyssey');
INSERT INTO SKIN VALUES('Sea Hunter Aatrox',750,'2015-07-23','False','Regular','Aatrox','sea-hunter');
INSERT INTO SKIN VALUES('Victorious Aatrox',null,'2019-11-21','True','Special Events','Aatrox','victorious');
INSERT INTO SKIN VALUES('Blood Moon Aatrox',1350,'2019-01-10','False','Epic','Aatrox','blood-moon');
INSERT INTO SKIN VALUES('Crime City Nightmare Akali',1350,'2021-08-26','False','Epic','Akali','crime-city-nightmare');
INSERT INTO SKIN VALUES('Stinger Akali',520,'2010-05-11','False','Regular','Akali','stinger');
INSERT INTO SKIN VALUES('K/DA ALL OUT Akali',1350,'2020-10-29','True','Epic','Akali','k-da-all-out');
INSERT INTO SKIN VALUES('Infernal Akali',520,'2010-05-11','False','Regular','Akali','infernal');
INSERT INTO SKIN VALUES('True Damage Akali',1350,'2019-11-10','True','Epic','Akali','true-damage');
INSERT INTO SKIN VALUES('All-star Akali',975,'2010-06-28','False','Regular','Akali','all-star');
INSERT INTO SKIN VALUES('PROJECT: Akali',1350,'2019-08-01','True','Epic','Akali','project');
INSERT INTO SKIN VALUES('Nurse Akali',975,'2011-01-04','True','Regular','Akali','nurse');
INSERT INTO SKIN VALUES('Cosmic Queen Ashe',1350,'2018-08-21','True','Epic','Ashe','cosmic-queen');
INSERT INTO SKIN VALUES('Woad Ashe',520,'2010-07-19','False','Regular','Ashe','woad');
INSERT INTO SKIN VALUES('Championship Ashe',1350,'2017-09-12','True','Epic','Ashe','championship');
INSERT INTO SKIN VALUES('Queen Ashe',975,'2010-09-21','False','Regular','Ashe','queen');
INSERT INTO SKIN VALUES('PROJECT: Ashe',1820,'2016-08-02','False','Legendary','Ashe','project');
INSERT INTO SKIN VALUES('Amethyst Ashe',975,'2011-11-15','False','Regular','Ashe','amethyst');

--스킨 변경점
INSERT INTO SKIN_CHANGES VALUES('Justicar Aatrox','True','False');
INSERT INTO SKIN_CHANGES VALUES('Arcana Ahri','True','False');
INSERT INTO SKIN_CHANGES VALUES('Dynasty Ahri','True','False');
INSERT INTO SKIN_CHANGES VALUES('K/DA Akali','True','False');
INSERT INTO SKIN_CHANGES VALUES('Cyber Pop Akshan','True','False');
INSERT INTO SKIN_CHANGES VALUES('Conqueror Alistar','True','False');
INSERT INTO SKIN_CHANGES VALUES('Hextech Amumu','True','False');
INSERT INTO SKIN_CHANGES VALUES('Cosmic Flight Anivia','True','False');
INSERT INTO SKIN_CHANGES VALUES('Red Riding Annie','False','False');
INSERT INTO SKIN_CHANGES VALUES('Spirit Blossom Aphelios','True','False');
INSERT INTO SKIN_CHANGES VALUES('High Noon Ashe','True','False');
INSERT INTO SKIN_CHANGES VALUES('Storm Dragon Aurelion Sol','True','False');
INSERT INTO SKIN_CHANGES VALUES('Galactic Azir','True','False');
INSERT INTO SKIN_CHANGES VALUES('Bard Bard','True','False');
INSERT INTO SKIN_CHANGES VALUES('Battle Boss Bel''Veth','True','False'); --
INSERT INTO SKIN_CHANGES VALUES('Goalkeeper Blitzcrank','False','False');
INSERT INTO SKIN_CHANGES VALUES('Vandal Brand','False','False');
INSERT INTO SKIN_CHANGES VALUES('Sugar Rush Braum','True','False');
INSERT INTO SKIN_CHANGES VALUES('Pool Party Caitlyn','True','False');
INSERT INTO SKIN_CHANGES VALUES('Strike Commander Camille','True','False');
INSERT INTO SKIN_CHANGES VALUES('Coven Cassiopeia','True','False');
INSERT INTO SKIN_CHANGES VALUES('Prehistoric cho''gath','True','False'); --
INSERT INTO SKIN_CHANGES VALUES('Corgi Corki','True','False');
INSERT INTO SKIN_CHANGES VALUES('Spirit Blossom Darius','True','False');
INSERT INTO SKIN_CHANGES VALUES('Sentinel Diana','True','False');
INSERT INTO SKIN_CHANGES VALUES('Ruined Draven','True','False');
INSERT INTO SKIN_CHANGES VALUES('Frozen Prince Mundo','True','False'); --
INSERT INTO SKIN_CHANGES VALUES('Firelight Ekko','True','False');
INSERT INTO SKIN_CHANGES VALUES('Bewitching Elise','True','False');
INSERT INTO SKIN_CHANGES VALUES('Tango Evelynn','True','False');
INSERT INTO SKIN_CHANGES VALUES('SSG Ezreal','True','False');
INSERT INTO SKIN_CHANGES VALUES('Praetorian Fiddlesticks','True','False');
INSERT INTO SKIN_CHANGES VALUES('iG Fiora','True','False');
INSERT INTO SKIN_CHANGES VALUES('Super Galaxy Fizz','True','False');
INSERT INTO SKIN_CHANGES VALUES('Commando Galio','True','False');
INSERT INTO SKIN_CHANGES VALUES('Pool Party Gangplank','True','False');
INSERT INTO SKIN_CHANGES VALUES('Mecha Kingdoms Garen','True','False');
INSERT INTO SKIN_CHANGES VALUES('Elderwood Gnar','True','False');
INSERT INTO SKIN_CHANGES VALUES('Warden Gragas','True','False');
INSERT INTO SKIN_CHANGES VALUES('Hired Gun Graves','False','False');
INSERT INTO SKIN_CHANGES VALUES('High Noon Hecarim','True','False');
INSERT INTO SKIN_CHANGES VALUES('Dragon Trainer Heimerdinger','True','False');
INSERT INTO SKIN_CHANGES VALUES('Cosmic Invoker Illaoi','True','False');
INSERT INTO SKIN_CHANGES VALUES('PROJECT: Irelia','True','False');
INSERT INTO SKIN_CHANGES VALUES('Dunkmaster Ivern','True','False');
INSERT INTO SKIN_CHANGES VALUES('Cyber Halo Janna','True','False');
INSERT INTO SKIN_CHANGES VALUES('Worlds 2021 Jarvan IV','True','False'); --
INSERT INTO SKIN_CHANGES VALUES('God Staff Jax','True','False');
INSERT INTO SKIN_CHANGES VALUES('Dark Cosmic Jhin','True','False');
INSERT INTO SKIN_CHANGES VALUES('Resistance Jayce','True','False');
INSERT INTO SKIN_CHANGES VALUES('Lunar Eclipse Aatrox','True','False');
INSERT INTO SKIN_CHANGES VALUES('Mecha Aatrox','True','False');
INSERT INTO SKIN_CHANGES VALUES('Odyssey Aatrox','True','False');
INSERT INTO SKIN_CHANGES VALUES('Sea Hunter Aatrox','False','False');
INSERT INTO SKIN_CHANGES VALUES('Victorious Aatrox','True','False');
INSERT INTO SKIN_CHANGES VALUES('Blood Moon Aatrox','True','False');
INSERT INTO SKIN_CHANGES VALUES('Crime City Nightmare Akali','True','False');
INSERT INTO SKIN_CHANGES VALUES('Stinger Akali','False','False');
INSERT INTO SKIN_CHANGES VALUES('K/DA ALL OUT Akali','True','False');
INSERT INTO SKIN_CHANGES VALUES('Infernal Akali','True','False');
INSERT INTO SKIN_CHANGES VALUES('True Damage Akali','True','False');
INSERT INTO SKIN_CHANGES VALUES('All-star Akali','False','False');
INSERT INTO SKIN_CHANGES VALUES('PROJECT: Akali','True','False');
INSERT INTO SKIN_CHANGES VALUES('Nurse Akali','True','False');
INSERT INTO SKIN_CHANGES VALUES('Cosmic Queen Ashe','True','False');
INSERT INTO SKIN_CHANGES VALUES('Woad Ashe','True','False');
INSERT INTO SKIN_CHANGES VALUES('Championship Ashe','True','False');
INSERT INTO SKIN_CHANGES VALUES('Queen Ashe','False','False');
INSERT INTO SKIN_CHANGES VALUES('PROJECT: Ashe','True','False');
INSERT INTO SKIN_CHANGES VALUES('Amethyst Ashe','True','False');

-- 유저
INSERT INTO USERS VALUES('zJYzMBFVI','T^rHlJ%UoV','Leofwine_draca','zJYzMBFVI@naver.com');
INSERT INTO USERS VALUES('ZxxhUex','Ry7ZUmq1%0x','kosmasp','ZxxhUex@daum.net');
INSERT INTO USERS VALUES('HfkF9l','7gwsBqmJh&L','Tweekums','HfkF9l@kakao.com');
INSERT INTO USERS VALUES('BPjPLa','6mbXrVmE8Rez','FeastMode','BPjPLa@kakao.com');
INSERT INTO USERS VALUES('heXXeWWI','KmmH@9cVGj#','Irishchatter','heXXeWWI@daum.net');
INSERT INTO USERS VALUES('BJ0OfE8z','z#fdzHhat','Edvis-1997','BJ0OfE8z@gmail.com');
INSERT INTO USERS VALUES('lvVvhycg','osz1TLFO','John6Daniels','lvVvhycg@daum.net');
INSERT INTO USERS VALUES('6l6hY6Qs','7rd4ZD!nJ','RosanaBotafogo','6l6hY6Qs@naver.com');
INSERT INTO USERS VALUES('KYrbz8rPL','v%*flvyYM','billcr12','KYrbz8rPL@gmail.com');
INSERT INTO USERS VALUES('bgGfJi','55o!P!k24C&','alindsay-al','bgGfJi@gmail.com');
INSERT INTO USERS VALUES('UNkuS4','m824XO!!S','andrewchristianjr','UNkuS4@naver.com');
INSERT INTO USERS VALUES('jKAsL741','vAWDD5#pe','ks-60500','jKAsL741@gmail.com');
INSERT INTO USERS VALUES('laGpSQ','#@xXzte1se','dwp1948','laGpSQ@gmail.com');
INSERT INTO USERS VALUES('yuLtJaWH','O5MkkD%%','qui_j','yuLtJaWH@naver.com');
INSERT INTO USERS VALUES('Xza4JQa5U','hsTFq1pD*','zhyarTheChosen','Xza4JQa5U@daum.net');
INSERT INTO USERS VALUES('fIWk47','FZH1t!q$BQ4','Xstal','fIWk47@gmail.com');
INSERT INTO USERS VALUES('ObIPxdfbS','NL5lYSb6e','gianmarcoronconi','ObIPxdfbS@gmail.com');
INSERT INTO USERS VALUES('lcR6um7D','gvVJUw#qxEpa','MadamWarden','lcR6um7D@gmail.com');
INSERT INTO USERS VALUES('ZrzH8C7M','2$FEdYD6&zuw','gedikreverdi','ZrzH8C7M@kakao.com');
INSERT INTO USERS VALUES('xYYpl7Djn','ip$vk$r4hk','surfisfun','xYYpl7Djn@kakao.com');
INSERT INTO USERS VALUES('rtDcoDybU','ew^3so5ynWt','Horror_Flick_Fanatic','rtDcoDybU@daum.net');
INSERT INTO USERS VALUES('UjYeICwT','ff6pYWSl9%8I','Movi3DO','UjYeICwT@gmail.com');
INSERT INTO USERS VALUES('rTuV7v','EvoS8iWjVO','djurrepower','rTuV7v@gmail.com');
INSERT INTO USERS VALUES('72ME5Qh','7OdnIYOn0!x','SoumikBanerjee25','72ME5Qh@naver.com');
INSERT INTO USERS VALUES('xDFYepT8g','PuV9quRyX','bshaef','xDFYepT8g@daum.net');
INSERT INTO USERS VALUES('dFaQcwP','4KUdh^S88@9s','aboalhyjaa','dFaQcwP@naver.com');
INSERT INTO USERS VALUES('tCgKgulzb','W9#MbGCk','chunkylefunga','tCgKgulzb@gmail.com');
INSERT INTO USERS VALUES('3mqtk9Bd','&ayCYJ*r^uP','Dragonborn64','3mqtk9Bd@naver.com');
INSERT INTO USERS VALUES('ea2lIjn','Tvdtc*b8z','lareval','ea2lIjn@gmail.com');
INSERT INTO USERS VALUES('ecBBuXIO','^Hvm!8wxx6','AvionPrince16','ecBBuXIO@daum.net');
INSERT INTO USERS VALUES('sJXxcrc','R3$v1@46','alcantaraj-16594','sJXxcrc@gmail.com');
INSERT INTO USERS VALUES('ZI8cdjZ','2oZo5KV8!E','PedroPires90','ZI8cdjZ@kakao.com');
INSERT INTO USERS VALUES('NEdrgHG3V','iusuUKY@3ClL','paulwattriley','NEdrgHG3V@kakao.com');
INSERT INTO USERS VALUES('X51muI4O','VY#4DM!dD8','drpainters','X51muI4O@kakao.com');
INSERT INTO USERS VALUES('6zkRaW6','yJojmwYR*hPH','svader','6zkRaW6@kakao.com');
INSERT INTO USERS VALUES('su5OvxND','7jOr5F0OoT','colewaters','su5OvxND@daum.net');
INSERT INTO USERS VALUES('aIoUDDP86','ZCJgiCwIW','shanayneigh','aIoUDDP86@daum.net');
INSERT INTO USERS VALUES('vA5IpvVAS','&xP1N8YLm0N','AJ_McAninch','vA5IpvVAS@kakao.com');
INSERT INTO USERS VALUES('83f83uq','39i4UIc4j','nicorip22','83f83uq@gmail.com');
INSERT INTO USERS VALUES('DVNCy3wx','vUadIBMACHEo','backup-50362','DVNCy3wx@naver.com');
INSERT INTO USERS VALUES('yLfyHBe','m263GXa44x&N','tesswysko','yLfyHBe@naver.com');
INSERT INTO USERS VALUES('2Ywrmm','C!#JRWJQS','sriramthestranger','2Ywrmm@gmail.com');
INSERT INTO USERS VALUES('1jLhG3q','s37T%ojv56oe','mikeiskorn','1jLhG3q@gmail.com');
INSERT INTO USERS VALUES('63Epthg2K','yu7DXYWLkRk','efd-10467','63Epthg2K@gmail.com');
INSERT INTO USERS VALUES('jwOdxV','AF3k75g5YJs7','root_king','jwOdxV@kakao.com');
INSERT INTO USERS VALUES('nQPD69Ds','O&IwWhQWeKS','pranayjalvi','nQPD69Ds@naver.com');
INSERT INTO USERS VALUES('m7GYDwcJH','dGoeHrUM','gallagherkellie','m7GYDwcJH@daum.net');
INSERT INTO USERS VALUES('6hlFQB','HxUYhRIwQ','laragi','6hlFQB@gmail.com');
INSERT INTO USERS VALUES('Ly0EO9H','U25knywbrjM','dumsumdumfai','Ly0EO9H@gmail.com');
INSERT INTO USERS VALUES('wAcnEwn','maR%7FoDcqp','TheVictoriousV','wAcnEwn@naver.com');
INSERT INTO USERS VALUES('mwUreLLS','SfVJna^5qqht','jakethesnake-42007','mwUreLLS@kakao.com');
INSERT INTO USERS VALUES('ctVHOuyJU','n!1JgsoPEOw','therskybznuiss','ctVHOuyJU@kakao.com');
INSERT INTO USERS VALUES('9ZiuP29','N2E2#3O0','AdrenalinDragon','9ZiuP29@gmail.com');
INSERT INTO USERS VALUES('C7pRJNVWk','o*45wfaiKJ','alaningle7','C7pRJNVWk@naver.com');
INSERT INTO USERS VALUES('NoCHbT0','HaFDiPbQ72','peeedeee-94281','NoCHbT0@kakao.com');
INSERT INTO USERS VALUES('5dqwRF','e3Dql&I#','nidhunmoviebuff','5dqwRF@naver.com');
INSERT INTO USERS VALUES('ZhIndON','wob@DBC^U3','nkishudak','ZhIndON@kakao.com');
INSERT INTO USERS VALUES('paGm1G9B','sI5$8n*ydnw','Ahmedfadil00','paGm1G9B@naver.com');
INSERT INTO USERS VALUES('9Iia1RY5r','005j@Bx7M','koofasa','9Iia1RY5r@naver.com');
INSERT INTO USERS VALUES('KF6sGt','hy16RXD5mL','polsixe','KF6sGt@daum.net'); --
INSERT INTO USERS VALUES('eXS4CUB','3FyBaSiH','jere_zabala','eXS4CUB@naver.com');
INSERT INTO USERS VALUES('SNCDM1Olu','zGrNof9!6BD','saphira_dragon-80270','SNCDM1Olu@gmail.com');
INSERT INTO USERS VALUES('2xJbnJggz','mWKA&ZQqass','FKDZ','2xJbnJggz@naver.com');
INSERT INTO USERS VALUES('zEMH3b5Y','Jt#Qn@zbL!RC','Radu_A','zEMH3b5Y@kakao.com');
INSERT INTO USERS VALUES('yv5z8Wrku','N0vQ^7%cvKJ','Mike_T-Little_Mtn_Sound_Archive','yv5z8Wrku@daum.net');
INSERT INTO USERS VALUES('wEtIJS','DhFD6iCzn','POIguy','wEtIJS@naver.com');
INSERT INTO USERS VALUES('KhrKlOT','BjKtJIq!','howboutthisone_huh','KhrKlOT@kakao.com');
INSERT INTO USERS VALUES('OevAEypP','5JQ$q$giBU','sini-200','OevAEypP@gmail.com');
INSERT INTO USERS VALUES('LoG5SYnm','&yriql&dbel5','Nightmarelogic','LoG5SYnm@gmail.com'); --
INSERT INTO USERS VALUES('RAWR1O6','neyFQ^7fY34','snperera','RAWR1O6@kakao.com');


INSERT INTO RATING VALUES('zJYzMBFVI','Justicar Aatrox',4);
INSERT INTO RATING VALUES('ZxxhUex','Arcana Ahri',3);
INSERT INTO RATING VALUES('HfkF9l','K/DA Akali',4);
INSERT INTO RATING VALUES('BPjPLa','Cyber Pop Akshan',1);
INSERT INTO RATING VALUES('heXXeWWI','Conqueror Alistar',1);
INSERT INTO RATING VALUES('BJ0OfE8z','Hextech Amumu',3);
INSERT INTO RATING VALUES('lvVvhycg','Cosmic Flight Anivia',5);
INSERT INTO RATING VALUES('6l6hY6Qs','Red Riding Annie',4);
INSERT INTO RATING VALUES('KYrbz8rPL','Spirit Blossom Aphelios',1);
INSERT INTO RATING VALUES('bgGfJi','High Noon Ashe',1);
INSERT INTO RATING VALUES('UNkuS4','Storm Dragon Aurelion Sol',4); --
INSERT INTO RATING VALUES('jKAsL741','Galactic Azir',5);
INSERT INTO RATING VALUES('laGpSQ','Bard Bard',4);
INSERT INTO RATING VALUES('yuLtJaWH','Battle Boss Bel''Veth',3); --
INSERT INTO RATING VALUES('Xza4JQa5U','Goalkeeper Blitzcrank',1);
INSERT INTO RATING VALUES('fIWk47','Vandal Brand',4);
INSERT INTO RATING VALUES('ObIPxdfbS','Sugar Rush Braum',2);
INSERT INTO RATING VALUES('lcR6um7D','Pool Party Caitlyn',2);
INSERT INTO RATING VALUES('ZrzH8C7M','Strike Commander Camille',3);
INSERT INTO RATING VALUES('xYYpl7Djn','Coven Cassiopeia',5);
INSERT INTO RATING VALUES('rtDcoDybU','Prehistoric cho''gath',5); --
INSERT INTO RATING VALUES('UjYeICwT','Corgi Corki',5);
INSERT INTO RATING VALUES('rTuV7v','Spirit Blossom Darius',5);
INSERT INTO RATING VALUES('72ME5Qh','Sentinel Diana',3);
INSERT INTO RATING VALUES('xDFYepT8g','Ruined Draven',3);
INSERT INTO RATING VALUES('dFaQcwP','Frozen Prince Mundo',3); --
INSERT INTO RATING VALUES('tCgKgulzb','Firelight Ekko',3);
INSERT INTO RATING VALUES('3mqtk9Bd','Bewitching Elise',3);
INSERT INTO RATING VALUES('ea2lIjn','Tango Evelynn',3);
INSERT INTO RATING VALUES('ecBBuXIO','SSG Ezreal',3);
INSERT INTO RATING VALUES('sJXxcrc','Praetorian Fiddlesticks',2);
INSERT INTO RATING VALUES('ZI8cdjZ','iG Fiora',3);
INSERT INTO RATING VALUES('NEdrgHG3V','Super Galaxy Fizz',5);
INSERT INTO RATING VALUES('X51muI4O','Commando Galio',5);
INSERT INTO RATING VALUES('6zkRaW6','Pool Party Gangplank',5);
INSERT INTO RATING VALUES('su5OvxND','Mecha Kingdoms Garen',3);
INSERT INTO RATING VALUES('aIoUDDP86','Elderwood Gnar',1);
INSERT INTO RATING VALUES('vA5IpvVAS','Warden Gragas',5);
INSERT INTO RATING VALUES('83f83uq','Hired Gun Graves',4);
INSERT INTO RATING VALUES('DVNCy3wx','High Noon Hecarim',3);
INSERT INTO RATING VALUES('yLfyHBe','Dragon Trainer Heimerdinger',2);
INSERT INTO RATING VALUES('2Ywrmm','Cosmic Invoker Illaoi',4);
INSERT INTO RATING VALUES('1jLhG3q','PROJECT: Irelia',3);
INSERT INTO RATING VALUES('63Epthg2K','Dunkmaster Ivern',2); --
INSERT INTO RATING VALUES('jwOdxV','Cyber Halo Janna',2);
INSERT INTO RATING VALUES('nQPD69Ds','Worlds 2021 Jarvan IV',5); --
INSERT INTO RATING VALUES('m7GYDwcJH','God Staff Jax',4);
INSERT INTO RATING VALUES('6hlFQB','Dynasty Ahri',1); --
INSERT INTO RATING VALUES('Ly0EO9H','Dark Cosmic Jhin',3);
INSERT INTO RATING VALUES('wAcnEwn','Resistance Jayce',4);
INSERT INTO RATING VALUES('mwUreLLS','Mecha Aatrox',3);
INSERT INTO RATING VALUES('ctVHOuyJU','Odyssey Aatrox',4);
INSERT INTO RATING VALUES('9ZiuP29','Sea Hunter Aatrox',1);
INSERT INTO RATING VALUES('C7pRJNVWk','Victorious Aatrox',2);
INSERT INTO RATING VALUES('NoCHbT0','Blood Moon Aatrox',2);
INSERT INTO RATING VALUES('5dqwRF','Crime City Nightmare Akali',4);
INSERT INTO RATING VALUES('ZhIndON','Stinger Akali',1);
INSERT INTO RATING VALUES('paGm1G9B','K/DA ALL OUT Akali',5);
INSERT INTO RATING VALUES('9Iia1RY5r','Infernal Akali',1);
INSERT INTO RATING VALUES('LoG5SYnm','True Damage Akali',3);
INSERT INTO RATING VALUES('KF6sGt','All-star Akali',5);
INSERT INTO RATING VALUES('eXS4CUB','PROJECT: Akali',1);
INSERT INTO RATING VALUES('SNCDM1Olu','Nurse Akali',1);
INSERT INTO RATING VALUES('2xJbnJggz','Cosmic Queen Ashe',3);
INSERT INTO RATING VALUES('zEMH3b5Y','Woad Ashe',2);
INSERT INTO RATING VALUES('yv5z8Wrku','Championship Ashe',3);
INSERT INTO RATING VALUES('wEtIJS','Queen Ashe',2);
INSERT INTO RATING VALUES('KhrKlOT','PROJECT: Ashe',3);
INSERT INTO RATING VALUES('OevAEypP','Amethyst Ashe',5);
INSERT INTO RATING VALUES('RAWR1O6','Lunar Eclipse Aatrox',4);

INSERT INTO COMMENTS VALUES('zJYzMBFVI','Leofwine_draca','I am coming to the borders and I will kill you all,','2021-10-09', 'Justicar Aatrox');
INSERT INTO COMMENTS VALUES('ZxxhUex','kosmasp','im getting on borderlands and i will kill you all,','2021-10-10', 'Arcana Ahri');
INSERT INTO COMMENTS VALUES('HfkF9l','Tweekums','im coming on borderlands and i will murder you all,','2021-10-11', 'K/DA Akali');
INSERT INTO COMMENTS VALUES('BPjPLa','FeastMode','im getting on borderlands 2 and i will murder you me all,','2021-10-09', 'Cyber Pop Akshan');
INSERT INTO COMMENTS VALUES('heXXeWWI','Irishchatter','im getting into borderlands and i can murder you all,','2021-10-08', 'Conqueror Alistar');
INSERT INTO COMMENTS VALUES('BJ0OfE8z','Edvis-1997','So I spent a few hours making something for fun. . . If you don''t know I am a HUGE @Borderlands fan and Maya is one of my favorite characters. So I decided to make myself a wallpaper for my PC. . Here is the original image versus the creation I made :) Enjoy! pic.twitter.com/mLsI5wf9Jg','2021-10-04', 'Hextech Amumu');
INSERT INTO COMMENTS VALUES('lvVvhycg','John6Daniels','So I spent a couple of hours doing something for fun... If you don''t know that i''m a huge @ Borderlands fan and Maya is one of my favorite characters, I decided to make a wallpaper for my PC.. here''s the original picture compared to the creation I made:) Have fun! pic.twitter.com / mLsI5wf9Jg','2021-10-15', 'Cosmic Flight Anivia');
INSERT INTO COMMENTS VALUES('6l6hY6Qs','RosanaBotafogo','So I spent a few hours doing something for fun... If you don''t know i''m a HUGE @ Borderlands fan and Maya is one of my favorite characters.','2021-10-12', 'Red Riding Annie');
INSERT INTO COMMENTS VALUES('KYrbz8rPL','billcr12','So I spent a few hours making something for fun. . . If you don''t know I am a HUGE RhandlerR fan and Maya is one of my favorite characters. So I decided to make myself a wallpaper for my PC. . Here is the original image versus the creation I made :) Enjoy! pic.twitter.com/mLsI5wf9Jg','2021-10-14', 'Spirit Blossom Aphelios');
INSERT INTO COMMENTS VALUES('bgGfJi','alindsay-al','2010 So I spent a few hours making something for fun. . . If you don''t know I am a HUGE RhandlerR fan and Maya is one of my favorite characters. So I decided to make myself a wallpaper for my PC. . Here is the original image versus the creation I made :) Enjoy! pic.twitter.com/mLsI5wf9Jg','2021-10-10', 'High Noon Ashe');
INSERT INTO COMMENTS VALUES('UNkuS4','andrewchristianjr','was','2021-09-29', 'Storm Dragon Aurelion Sol');
INSERT INTO COMMENTS VALUES('jKAsL741','ks-60500','Rock-Hard La Varlope, RARE & POWERFUL, HANDSOME JACKPOT, Borderlands 3 (Xbox) dlvr.it/RMTrgF  ','2021-09-25', 'Galactic Azir');
INSERT INTO COMMENTS VALUES('laGpSQ','dwp1948','Rock-Hard La Varlope, RARE & POWERFUL, HANDSOME JACKPOT, Borderlands 3 (Xbox) dlvr.it / RMTrgF','2021-09-24', 'Bard Bard');
INSERT INTO COMMENTS VALUES('yuLtJaWH','qui_j','Rock-Hard La Varlope, RARE & POWERFUL, HANDSOME JACKPOT, Borderlands 3 (Xbox) dfr.it / RMTrgF','2021-10-06', 'Battle Boss Bel''Veth');
INSERT INTO COMMENTS VALUES('Xza4JQa5U','zhyarTheChosen','Rock-Hard La Vita, RARE BUT POWERFUL, HANDSOME JACKPOT, Borderlands 1 (Xbox) dlvr.it/RMTrgF','2021-10-06', 'Goalkeeper Blitzcrank');
INSERT INTO COMMENTS VALUES('fIWk47','Xstal','Live Rock - Hard music La la Varlope, RARE & the POWERFUL, Live HANDSOME i JACKPOT, Borderlands 3 ( Sega Xbox ) dlvr. From it / e RMTrgF','2021-10-14', 'Vandal Brand');
INSERT INTO COMMENTS VALUES('ObIPxdfbS','gianmarcoronconi','I-Hard like me, RARE LONDON DE, HANDSOME 2011, Borderlands 3 (Xbox) dlvr.it/RMTrgF','2021-10-04', 'Sugar Rush Braum');
INSERT INTO COMMENTS VALUES('lcR6um7D','MadamWarden','that was the first borderlands session in a long time where i actually had a really satisfying combat experience. i got some really good kills','2021-10-09', 'Pool Party Caitlyn');
INSERT INTO COMMENTS VALUES('ZrzH8C7M','gedikreverdi','this was the first Borderlands session in a long time where i actually had a really satisfying fighting experience. i got some really good kills','2021-10-11', 'Strike Commander Camille');
INSERT INTO COMMENTS VALUES('xYYpl7Djn','surfisfun','that was the first borderlands session in a long time where i actually had a really satisfying combat experience. i got some really good kills','2021-09-20', 'Coven Cassiopeia');
INSERT INTO COMMENTS VALUES('rtDcoDybU','Horror_Flick_Fanatic','that was the first borderlands session in a long time where i actually enjoyed a really satisfying combat experience. i got some rather good kills','2021-10-07', 'Prehistoric cho''gath');
INSERT INTO COMMENTS VALUES('UjYeICwT','Movi3DO','that I was the first real borderlands session in a nice long wait time where i actually had a really satisfying combat experience. and i got some really good kills','2021-09-23', 'Corgi Corki');
INSERT INTO COMMENTS VALUES('rTuV7v','djurrepower','that was the first borderlands session in a hot row where i actually had a really bad combat experience. i did some really good kills','2021-10-09', 'Spirit Blossom Darius');
INSERT INTO COMMENTS VALUES('72ME5Qh','SoumikBanerjee25','the biggest dissappoinment in my life came out a year ago fuck borderlands 3','2021-10-08', 'Sentinel Diana');
INSERT INTO COMMENTS VALUES('xDFYepT8g','bshaef','The biggest disappointment of my life came a year ago.','2021-10-07', 'Ruined Draven');
INSERT INTO COMMENTS VALUES('dFaQcwP','aboalhyjaa','The biggest disappointment of my life came a year ago.','2021-09-23', 'Frozen Prince Mundo');
INSERT INTO COMMENTS VALUES('tCgKgulzb','chunkylefunga','the biggest dissappoinment in my life coming out a year ago fuck borderlands 3','2021-09-26', 'Firelight Ekko');
INSERT INTO COMMENTS VALUES('3mqtk9Bd','Dragonborn64','For the biggest male dissappoinment in my life came hanging out a year time ago fuck borderlands 3','2021-10-02', 'Bewitching Elise');
INSERT INTO COMMENTS VALUES('ea2lIjn','lareval','the biggest dissappoinment in my life came back last year ago fuck borderlands last','2021-09-26', 'Tango Evelynn');
INSERT INTO COMMENTS VALUES('ecBBuXIO','AvionPrince16','WE FINISHED BORDERLANDS 3 FINALLY YAS! Thank you for hanging out everyone! It was fun. I will try to stream tomorrow but if not I might so some IRL streams while awayu. We shall see. Thank you so much for the raids @mompou_mumpow @MegaMagwitch and @KfdMitch.','2021-10-08', 'SSG Ezreal');
INSERT INTO COMMENTS VALUES('sJXxcrc','alcantaraj-16594','WE FINALLY FINALLY FIND BORDERLANDS 3 YES! Thank you all for hanging out! It was fun. i''ll try to stream tomorrow, but if not, maybe some IRL streams. we''ll see. Thanks for the raids @ mompou _ mumpow @ MegaMagwitch and @ KfdMitch.','2021-09-26', 'Praetorian Fiddlesticks');
INSERT INTO COMMENTS VALUES('ZI8cdjZ','PedroPires90','Thank you for hanging up everyone! It was fun. I''ll try to get a haircut tomorrow, but if it wasn''t for me, some IRL streams would still be in Hawaii. we''ll see. Thank you so much for the @ mompou _ mumpow @ MegaMagwife and @ fendMitch raids.','2021-10-03', 'iG Fiora');
INSERT INTO COMMENTS VALUES('NEdrgHG3V','paulwattriley','WE FINISHED BORDERLANDS 3 UPDATE YAS! Thank you for hanging out guys! It was fun. I will try to stream and even if not I might so some IRL streams while awayu. We shall go. Thank you so much for the raids @mompou_mumpow @MegaMagwitch and Hope.','2021-10-08', 'Super Galaxy Fizz');
INSERT INTO COMMENTS VALUES('X51muI4O','drpainters','WE FINISHED BORDERLANDS 3 AND FINALLY YAS! Thank you everyone for hanging out everyone! It was fun. I will try to make stream tomorrow but if not I might make so some IRL streams while awayu. 10 We never shall see. Thank you both so... much for the raids @mompou_mumpow or @MegaMagwitch and 4 @KfdMitch.','2021-10-09', 'Commando Galio');
INSERT INTO COMMENTS VALUES('6zkRaW6','svader','WE FINISHED BORDERLANDS 3 FINALLY YAS! Hey you for hanging out so! It was fun. I will try that stream tomorrow and if not I might use some IRL streams from awayu. We shall see. Thank you so much how many raids @mompou_mumpow did and their.','2021-10-07', 'Dynasty Ahri');
INSERT INTO COMMENTS VALUES('su5OvxND','colewaters','Man Gearbox really needs to fix this dissapointing drops in the new Borderlands 3 DLC cant be fine to farm bosses on Mayhem 10 to get 1 legendary drop while anywhere else i get 6-10 drops. . Really sucks alot','2021-10-13', 'Pool Party Gangplank');
INSERT INTO COMMENTS VALUES('aIoUDDP86','shanayneigh','Man Gearbox really needs to fix these disappointing drops in the new Borderlands 3 DLC for farm bosses on Mayhem 10 to get a legendary drop, while I get 6-10 drops elsewhere.','2021-09-25', 'Mecha Kingdoms Garen');
INSERT INTO COMMENTS VALUES('vA5IpvVAS','AJ_McAninch','Man Gearbox really needs to fix this disssapointing drops in the new Borderlands 3 DLC cant be fine to farm bosses on Mayhem 10 to get 1 legendary drop while elsewhere i get 6-10 drops... Really sucks alot','2021-10-05', 'Elderwood Gnar');
INSERT INTO COMMENTS VALUES('83f83uq','nicorip22','Man Bethesda really needs to fix this dissapointing drops and the new Borderlands 3 It cant be fine to farm bosses on Mayhem 10 to get 1 legendary drop while anywhere else i get 6-10 drops.. Really sucks...','2021-09-28', 'Warden Gragas');
INSERT INTO COMMENTS VALUES('DVNCy3wx','backup-50362','Man Gearbox really needs to fix this dissapointing drops in the completely new Borderlands 3 Days DLC i cant e be fine having to be farm bosses on Mayhem 10 to e get 1 legendary foot drop while anywhere else i get 6 - 10 drops.. It Really sucks to alot','2021-10-14', 'Hired Gun Graves');
INSERT INTO COMMENTS VALUES('yLfyHBe','tesswysko','<unk> Gearbox really time to fix this 10 drops in the new Borderlands 3 DLC or be fine to force bosses on Mayhem 10 to get a legendary drop while everyone else i get 6-10 drops.. Really needs alot','2021-10-14', 'High Noon Hecarim');
INSERT INTO COMMENTS VALUES('2Ywrmm','sriramthestranger','Check out this epic streamer!.  ','2021-10-04', 'Dragon Trainer Heimerdinger');
INSERT INTO COMMENTS VALUES('1jLhG3q','mikeiskorn','Check out this epic streamer!.','2021-10-12', 'Cosmic Invoker Illaoi');
INSERT INTO COMMENTS VALUES('63Epthg2K','efd-10467','Watch this epic striptease!.','2021-10-13', 'PROJECT: Irelia');
INSERT INTO COMMENTS VALUES('jwOdxV','root_king','Check out our epic streamer!.','2021-10-15', 'Dunkmaster Ivern');
INSERT INTO COMMENTS VALUES('nQPD69Ds','pranayjalvi','Check out this big epic streamer!.','2021-10-03', 'Cyber Halo Janna');
INSERT INTO COMMENTS VALUES('m7GYDwcJH','gallagherkellie','Check<unk> this epic streamer!.','2021-10-02', 'Worlds 2021 Jarvan IV');
INSERT INTO COMMENTS VALUES('6hlFQB','laragi','Blaming Sight for Tardiness! A little bit of borderlands. I got called in early for work tomorrow so I can''t make up time. Sorry my loves .  twitch.tv/punnisenpai','2021-09-22', 'God Staff Jax');
INSERT INTO COMMENTS VALUES('Ly0EO9H','dumsumdumfai','A bit of borderland. I was called to work tomorrow morning, so I can''t catch up. Sorry, my love. twitch.tv / punnisenpai','2021-10-10', 'Dark Cosmic Jhin');
INSERT INTO COMMENTS VALUES('wAcnEwn','TheVictoriousV','Guilty of sobriety! A bit of a borderline. I was called to work early tomorrow, so I can''t catch up.','2021-10-12', 'Resistance Jayce');
INSERT INTO COMMENTS VALUES('mwUreLLS','jakethesnake-42007','Blaming Sight for Tardiness! A little bit of borderlands. I got called in early for work tomorrow so I can''t make up time. Sorry my loves .  twitch.tv/punnisenpai','2021-09-26', 'Mecha Aatrox');
INSERT INTO COMMENTS VALUES('ctVHOuyJU','therskybznuiss','for Blaming Sight for Tardiness! A little bit of borderlands. I got called in early for work tomorrow so I can''t make up time. Sorry my loves .  twitch.tv/punnisenpai','2021-09-20', 'Odyssey Aatrox');
INSERT INTO COMMENTS VALUES('9ZiuP29','AdrenalinDragon','all','2021-10-04', 'Sea Hunter Aatrox');
INSERT INTO COMMENTS VALUES('C7pRJNVWk','alaningle7','why does like every man in borderlands have slicked back hair haven��t you heard of bangs you stupid assholes','2021-09-19', 'Victorious Aatrox');
INSERT INTO COMMENTS VALUES('NoCHbT0','peeedeee-94281','Why, like every man in border countries, have you not heard of bangs, you stupid assholes?','2021-10-09', 'Blood Moon Aatrox');
INSERT INTO COMMENTS VALUES('5dqwRF','nidhunmoviebuff','Why, like everyone else in the border countries, have your hair fallen off, have you not heard that you are stupid aliens?','2021-10-03', 'Crime City Nightmare Akali');
INSERT INTO COMMENTS VALUES('ZhIndON','nkishudak','why does like<unk> man in borderlands have slicked back hair or you heard of bangs you stupid assholes','2021-10-13', 'Stinger Akali');
INSERT INTO COMMENTS VALUES('paGm1G9B','Ahmedfadil00','why Beth does like every man in borderlands have she slicked that back hair haven �� t you heard enough of gray bangs you stupid assholes','2021-09-26', 'K/DA ALL OUT Akali');
INSERT INTO COMMENTS VALUES('9Iia1RY5r','koofasa','why does practically every man in France have slicked back hair haven��t you heard of bangs the greedy assholes','2021-10-03', 'Infernal Akali');
INSERT INTO COMMENTS VALUES('KF6sGt','polsixe','nan','2021-10-04', 'True Damage Akali');
INSERT INTO COMMENTS VALUES('eXS4CUB','jere_zabala','.. [','2021-10-04', 'All-star Akali');
INSERT INTO COMMENTS VALUES('SNCDM1Olu','saphira_dragon-80270','.. 45','2021-10-04', 'PROJECT: Akali');
INSERT INTO COMMENTS VALUES('2xJbnJggz','FKDZ','.. [','2021-09-30', 'Nurse Akali');
INSERT INTO COMMENTS VALUES('zEMH3b5Y','Radu_A','.. what','2021-10-07', 'Cosmic Queen Ashe');
INSERT INTO COMMENTS VALUES('yv5z8Wrku','Mike_T-Little_Mtn_Sound_Archive','Going to finish up Borderlands 2 today. i''ve got some new commands set up and am looking forward to a good stream! Starting in about am hour!','2021-09-23', 'Woad Ashe');
INSERT INTO COMMENTS VALUES('wEtIJS','POIguy','I will finish Borderlands 2 today. I have some new commands set up and am looking forward to a good stream! Start in about an hour!','2021-10-14', 'Championship Ashe');
INSERT INTO COMMENTS VALUES('KhrKlOT','howboutthisone_huh','i''m going to finish Borderlands 2 today. I have some new commands installed and i''m looking forward to a good stream!','2021-10-06', 'Queen Ashe');
INSERT INTO COMMENTS VALUES('OevAEypP','sini-200','Going to finish up Borderlands 2 today. i''ve got some new events set up and am look forward to a good stream! Starting in about 20 hour!','2021-09-25', 'PROJECT: Ashe');
INSERT INTO COMMENTS VALUES('LoG5SYnm','Nightmarelogic','Going to finish finish cleaning up Borderlands 2 today. i''ve just got her some new commands set all up and am looking forward it to a good stream! Starting in about am hour!','2021-10-03', 'Amethyst Ashe');
INSERT INTO COMMENTS VALUES('RAWR1O6','snperera','Going to finish up volume 2 today. i''ve got some awesome server set up and is looking forward to a good stream! Starting in about am hour!','2021-10-08', 'Lunar Eclipse Aatrox');

commit;