CREATE TABLE SKIN(
    Skin_name VARCHAR2(50) NOT NULL PRIMARY KEY,
    Price Number,
    Launch_date DATE, 
    Chroma CHAR(5),
    Kind VARCHAR2(50),
    Champ_name VARCHAR2(50) NOT NULL,
    Uni_name VARCHAR2(50) NOT NULL);

CREATE TABLE CHAMPION(
    Name VARCHAR2(50) NOT NULL PRIMARY KEY,
    Title VARCHAR2(50),
    Class VARCHAR2(50),
    Region VARCHAR2(50),
    Release_Date DATE);

CREATE TABLE SKIN_UNIVERSE(
    Name VARCHAR2(50) NOT NULL PRIMARY KEY,
    Lore VARCHAR2(500)); --수정 필요할듯

CREATE TABLE SKIN_CHANGES(--weak entity --PK 수정필요?   
    Skin_name VARCHAR2(50) NOT NULL PRIMARY KEY,
    Effects VARCHAR2(50),
    Animations VARCHAR2(50));  
    
CREATE TABLE RATING(--weak entity
    Id VARCHAR2(50),
    Skin_name VARCHAR2(50) NOT NULL,
    Score Number,
    CONSTRAINT pk_Rating PRIMARY KEY(Id,Skin_name));
    
CREATE TABLE USERS(
    Id VARCHAR2(50) NOT NULL,
    Password VARCHAR2(50),
    Name VARCHAR2(50),
    Email VARCHAR2(50),
    UNIQUE(Id),
    UNIQUE(Name),
    CONSTRAINT pk_Users PRIMARY KEY(Id,Name)); 
    
CREATE TABLE COMMENTS(--PK 수정필요
    Id VARCHAR2(50) NOT NULL,
    User_name VARCHAR2(50),
    Content VARCHAR2(500),
    Created_Date DATE,
    Skin_name VARCHAR2(50) NOT NULL,
    CONSTRAINT pk_Comments PRIMARY KEY(Id,Skin_name));--수정 필요!!!

--외부키 추가
ALTER TABLE SKIN ADD FOREIGN KEY(Champ_name) REFERENCES CHAMPION(Name);
ALTER TABLE SKIN ADD FOREIGN KEY(Uni_name) REFERENCES SKIN_UNIVERSE(Name); --이건 아직 안 만들어서 인정
ALTER TABLE SKIN_CHANGES ADD FOREIGN KEY(Skin_name) REFERENCES SKIN(Skin_Name);
ALTER TABLE RATING ADD FOREIGN KEY(Id) REFERENCES USERS(Id); 
ALTER TABLE RATING ADD FOREIGN KEY(Skin_name) REFERENCES SKIN(Skin_Name);
ALTER TABLE COMMENTS ADD FOREIGN KEY(Id) REFERENCES USERS(Id); 
ALTER TABLE COMMENTS ADD FOREIGN KEY(User_name) REFERENCES USERS(Name); 
ALTER TABLE COMMENTS ADD FOREIGN KEY(Skin_name) REFERENCES SKIN(Skin_Name);